# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'awesome_print'
gem 'coffee-script'
gem 'guard'
gem 'guard-bundler'
gem 'guard-yield'
gem 'httparty'
gem 'pry'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
