directories %w[config coffee js].select { |d| Dir.exist?(d) ? d : UI.warning("Directory #{d} does not exist") }

require './lib/screeps.rb'

notification :terminal_notifier, app_name: "Screeps ::", activate: 'com.googlecode.iTerm2' if `uname` =~ /Darwin/

yield_options = {
  object: ::Screeps.new(ENV['token']),

  start: proc { |obj| obj.download },
  # stop: proc { |obj| obj.upload },

  run_on_modifications: proc { |obj, action, files| obj.sync(action, files) },
  run_on_additions: proc { |obj, action, files| obj.sync(action, files) },
  run_on_removals: proc { |obj, action, files| obj.sync(action, files) }
}

guard :yield, yield_options do
  watch(%r{(.*/[^.][^/]+\.js|coffee)})
end

guard :bundler do
  require 'guard/bundler'
  require 'guard/bundler/verify'
  helper = Guard::Bundler::Verify.new

  files = ['Gemfile']
  files += Dir['*.gemspec'] if files.any? { |f| helper.uses_gemspec?(f) }

  # Assume files are symlinked from somewhere
  files.each { |file| watch(helper.real_path(file)) }
end
